name: Azure app service deploy

on:
    push:
        branches:
            - main

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Setup Node.js version
              uses: actions/setup-node@v4
              with: 
                node-version: '20.7.x'
            - name: Install dependencies
              run: 
                npm install
                npm install express
                npm install ejs
                npm install dotenv
                npm install  pg
            - name: deploy to Azure App Service
              uses: azure/webapps-deploy@v2
              with:
                app-name: deliviotest
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                package: .

                  


